---
kind: pipeline
type: docker
name: publish-bot

steps:
- name: build-image
  image: plugins/docker
  settings:
    registry: git.kizaing.ca
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASS
    repo: git.kizaing.ca/kizaing/teletok
    tags: latest

# Commented out until stuff actually works
trigger:
  branch:
  - main
  event:
  - push