---
kind: pipeline
type: docker
name: publish-bot

steps:
- name: build-dotnet
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet publish

- name: build-image
  image: plugins/docker
  settings:
    registry: git.kizaing.ca
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASS
    repo: git.kizaing.ca/kizaing/TeleTok
    tags: latest
    platform: linux/amd64,linux/arm64


# Commented out until stuff actually works
#trigger:
#  branch:
#  - main
#  event:
#  - push